class AppRoutes {
  const AppRoutes._();

  static const home = '/home';
  static const shell = '/shell';
  static const detail = '/detail';
  static const user = '/user';
  static const welcome = '/welcome';
  static const login = '/login';
  static const verification = '/verification';
  static const setUpProfile = '/set-up-profile';
  static const chat = '/chat';
  static const chatDetail = '/chat-detail';
  static const contact = '/contact';
  static const userCall = '/user-call';
  static const profile = '/profile';
  static const editInfo = '/edit-info';
  static const setPhoto = '/set-photo';
  static const editName = '/edit-name';
  static const changeNumber = '/change-number';
  static const editUsername = '/edit-username';
  static const editBio = '/edit-bio';
  static const setting = '/setting';
  static const theme = '/theme';
  static const privacy = '/privacy';
  static const lastSeen = '/last-seen';
  static const profilePhotos = '/profile-photos';
  static const phoneNumberPrivacy = '/phone-number-privacy';
  static const bioPrivacy = '/bio-privacy';
  static const birthdayPrivacy = '/birthday-privacy';
  static const invitesPrivacy = '/invites-privacy';
  static const disappearingMessages = '/disappearing-messages';
  static const security             = '/security';
  static const twoStepVerification  = '/two-step-verification';
  static const devices              = '/devices';
  static const notifications        = '/notifications';
  static const ringtone             = '/ringtone';
  static const storage              = '/storage';
  static const helpCenter           = '/help-center';
  static const contactUs            = '/contact-us';
  static const privacyPolicy        = '/privacy-policy';
  static const addAccount           = '/add-account';
  static const chooseCountry        = '/choose-country';
  static const locationMap          = '/location-map';
  static const locationPicker       = '/location-picker';
}
